from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class ReleaseDocsTests(unittest.TestCase):
    def read_doc(self, name: str) -> str:
        return (ROOT / name).read_text(encoding="utf-8")

    def test_release_status_matrix_tracks_knowledge_os_kernels_and_shell(self) -> None:
        text = self.read_doc("docs/RELEASE_STATUS_MATRIX.md")

        for marker in [
            "knowledgeConsolePanel",
            "Knowledge Console Matrix",
            "knowledge_console.py",
            "tests/test_knowledge_console.py",
            "codex.mn.knowledgeConsoleMatrix.v1",
            "studioCanvasPanel",
            "operationLedgerDrawer",
            "sourceRegistryPanel",
            "verificationReportPanel",
            "externalGatewayPanel",
            "skillCenterPanel",
            "Object Intake router",
            "object_intake.py",
            "tests/test_object_intake.py",
            "codex.mn.objectIntake.v1",
            "Notebook Runbook",
            "notebook_runbook.py",
            "tests/test_notebook_runbook.py",
            "codex.mn.notebookRunbook.v1",
            "Object Task Composer",
            "object_task_composer.py",
            "tests/test_object_task_composer.py",
            "codex.mn.objectTaskComposer.v1",
            "codex.mn.objectTaskWorkflowCandidate.v1",
            "Workflow Builder Board",
            "workflow_builder.py",
            "tests/test_workflow_builder.py",
            "codex.mn.workflowBuilderBoard.v1",
            "workflowBuilderBoardPanel",
            "draft_candidates",
            "waiting_confirmation",
            "notebookObjectTaskComposer",
            "route_skill_center",
            "Live MN Object Kernel",
            "Source Registry action evidence",
            "External Automation Gateway v2",
            "Transactional Native Editor",
            "Workflow Runtime v2",
            "Skill Runtime v2",
            "Verification Agent",
            "codex.mn.verificationReport.v1",
            "final/v3 claim",
            "Arbitrary-document UI functional acceptance",
            "ui_functional_acceptance.py",
            "ui_functional_acceptance_summary",
            "uiFunctionalAcceptanceButton",
            "uiFunctionalAcceptanceLine",
            "UI 功能验收：PASS",
            "UI 功能验收",
            "codex-companion-ui-functional-acceptance-v1",
            "webview_static_controls",
            "webview_button_coverage",
            "webview_browser_render",
            "webview_browser_interaction",
            "webview_browser_actions",
            "webview_browser_write_actions",
            "sendButton",
            "Enter key",
            "conversation_new",
            "buttonActionDeltas",
            "conversationHistoryObjectButton",
            "conversationHistoryAllButton",
            "settings_update",
            "update_check",
            "open_url",
            "diagnose_permissions",
            "open_full_disk_access_settings",
            "request_pdf_cache",
            "request_native_capability_probe",
            "--browser-interaction",
            "--browser-actions",
            "--browser-write-actions",
            "request_mn_object_registry_scan",
            "mn_read_tree",
            "object_graph",
            "object_activity",
            "object_graph_relation_save",
            "notebook_runbook_preflight_record",
            "verificationRepairPlanRecommendedButton",
            "mindmapStudioVerifyButton",
            "mindmapStudioRollbackButton",
            "knowledge_index_search",
            "mindmap_target_status",
            "request_mindmap_diff_apply",
            "ai_edit_transaction_verify",
            "request_mn_object_existence_probe",
            "write_draft",
            "accept_ai_edit_transaction",
            "reject_ai_edit_transaction",
            "native_scope_guards",
            "Collect Single Document Acceptance.command",
            "single_document_acceptance.py",
            "single_document_acceptance",
            "singleDocumentAcceptanceButton",
            "realMnAcceptancePanel",
            "mainUiFunctionalAcceptanceButton",
            "realMnAcceptanceSafeEvidenceButton",
            "主工作台 Verification Center",
            "single_document_acceptance_summary",
            "本文档验收",
        ]:
            self.assertIn(marker, text)

        for stale in [
            "toolActionGrid",
            "goalActionStrip",
            "mainActionStack",
            "goalRunPanel",
            "sourceToolPanel",
            "stagedActionLine",
            "workflowActionPanel",
            "mindmapActionGrid",
            "moreToolsPanel",
            "moreToolsSummary",
            "secondaryToolsPanel",
            "secondaryToolsSummary",
            "workflowActionGrid",
            "workflowActionGroups",
            "goalActionPanel",
            "sourceActionGrid",
            "sourceToolGrid",
            "mindmapToolGrid",
            "文档与脑图工具条",
            "aiActionPanel/primaryActionGrid/sourceToolPanel/nodeToolPanel",
            "主操作网格是 5 格",
            "`goalToggleButton` 在 `primaryActionGrid`",
            "`goalActionStrip` 内联在常用任务标题区",
            "空闲为“开始”",
            "常用任务网格是 4+4 两行主操作区",
            "常用任务网格是 3+3 两行生成区",
            "原文工具折叠在 `secondaryToolsPanel`",
        ]:
            self.assertNotIn(stale, text)

    def test_release_docs_describe_goal_run_as_one_shot_not_persisted_context(self) -> None:
        combined = "\n".join(
            self.read_doc(name)
            for name in [
                "docs/PRODUCT_SPEC.md",
                "docs/USER_MANUAL.md",
                "docs/RELEASE_STATUS_MATRIX.md",
                "README.md",
            ]
        )

        self.assertIn("一次性长任务", combined)
        self.assertIn("不会保存成长期当前目标", combined)
        for stale in [
            "会保存当前目标",
            "状态栏显示当前目标摘要",
            "状态栏显示当前目标",
            "目标和上传文件能在",
        ]:
            self.assertNotIn(stale, combined)

    def test_ultimate_design_is_knowledge_agent_os_not_chat_plus_buttons(self) -> None:
        ultimate = self.read_doc("docs/ULTIMATE_PLUGIN_DESIGN.md")
        product_spec = self.read_doc("docs/PRODUCT_SPEC.md")
        manual = self.read_doc("docs/USER_MANUAL.md")
        combined = "\n".join([ultimate, product_spec, manual])

        for marker in [
            "MarginNote Knowledge Agent OS",
            "不是当前聊天插件的增强版",
            "双模式产品",
            "Chat Mode",
            "Agent Workspace Mode",
            "Knowledge OS Contract",
            "对象层",
            "操作层",
            "证据层",
            "聊天区只能作为命令入口",
            "聊天是入口，不是终局",
            "Agent Workspace 才是生产系统",
            "当前 0.4.x 是 Chat Mode + Agent Workspace 雏形",
            "从回答按钮升级到对象操作",
            "真实脑图工作台",
            "对象优先、操作优先、证据优先",
            "不得把现有控件堆叠当作终局",
            "Object Graph",
            "Object Browser",
            "object_browser",
            "mn_object_registry",
            "codex.mn.mnObjectRegistry.v1",
            "mnobj:note:<noteId>",
            "objectRegistryScanButton",
            "request_mn_object_registry_scan",
            "scan_mn_objects",
            "mnObjectRegistryScanFinished",
            "native_object_scan",
            "扫描对象会进入 Object Graph",
            "扫描证据存在后会直接打开 Object Browser",
            "open_source_registry",
            "已有可读材料时会打开 Source Registry",
            "没有原生扫描证据时会请求扫描 MN 对象",
            "open_object_browser",
            "open_mindmap_studio",
            "open_card_factory",
            "open_workflow_builder",
            "已有脑图树缓存后会直接打开 Mindmap Studio",
            "卡片覆盖` 轴会打开 Card Factory",
            "已有 run 后会直接打开 Workflow Builder",
            "Runbook 现在包含确认上下文、核对来源清单、扫描 MN 对象、读取脑图基线、检查卡片覆盖、生成操作计划、检查工作流、核对操作证据八步",
            "不会自动生成卡片",
            "native_object_scan 父子边",
            "点击扫描对象会打开该对象图谱",
            "点击扫描对象会打开该对象活动和账本",
            "扫描 MN",
            "mindmapTreeReadFinished",
            "objectBrowserPanel",
            "browserAction",
            "codex.mn.objectBrowser.v1",
            "Knowledge Index 实体",
            "knowledge_relation",
            "entityType/noteId/sourceRef/relations",
            "mn_note",
            "nativeMindmapTreeEvidence",
            "mindmap_tree_cache",
            "manual_relation",
            "object_graph_relation_save/delete",
            "object_graph_manual_relation",
            "manualRelation",
            "可编辑关系边",
            "Operation Ledger",
            "Knowledge Graph",
            "Workflow Runtime",
            "External Automation Gateway",
            "Skill Marketplace",
            "v3.0",
            "当前 0.4.x 不是终局",
            "AI Copilot 面板",
            "MNObject Registry",
            "Operation Compiler",
            "Object Browser",
            "Mindmap Studio",
            "Card Factory",
            "codex.mn.cardFactory.v1",
            "cardType",
            "reviewPrompt",
            "learningGoal",
            "卡片工厂",
            "Knowledge Graph Studio",
            "Workflow Builder",
            "Skill Center",
            "Operation Ledger Explorer",
            "只要首屏仍然像聊天框加按钮，就不算终极版",
            "v3 产品合约",
            "第一屏合约",
            "对象合约",
            "操作合约",
            "学习合约",
            "证据合约",
            "扩展合约",
            "如果一个版本的主要体验仍然是“问一句、看回答、点生成卡片/脑图、去设置里修问题”",
            "终局必须和当前版本拉开的可见断层",
            "当前 0.4.x 做不到的事",
            "终局验收不按按钮数量算",
            "默认入口必须能在 Chat Mode 和 Agent Workspace Mode 之间切换",
            "modeSwitchBar",
            "chatModeButton",
            "agentWorkspaceModeButton",
            "modeIntentLine",
            "activeProductMode",
            "lastWorkspacePane",
            "Workspace Navigator",
            "workspaceNavigator",
            "Knowledge Console Matrix",
            "knowledge_console.py",
            "codex.mn.knowledgeConsoleMatrix.v1",
            "Object Intake",
            "object_intake.py",
            "codex.mn.objectIntake.v1",
            "Object Task Composer",
            "object_task_composer.py",
            "codex.mn.objectTaskComposer.v1",
            "codex.mn.objectTaskDraft.v1",
            "codex.mn.objectTaskWorkflowCandidate.v1",
            "Workflow Builder Board",
            "workflow_builder.py",
            "codex.mn.workflowBuilderBoard.v1",
            "workflowBuilderBoardPanel",
            "draft_candidates",
            "waiting_confirmation",
            "workflow 候选",
            "启动候选必须继续经过 Workflow Runtime",
            "Object Task Composer`，把对象路线转成任务草案和 workflow 候选",
            "route_source_registry",
            "route_object_browser",
            "route_mindmap_studio",
            "route_card_factory",
            "route_workflow_builder",
            "route_skill_center",
            "route_verification_center",
            "用户不需要先发 prompt 才知道能做什么",
            "Mindmap Studio",
            "Card Factory",
            "Operation Ledger",
            "Workflow Builder",
            "Skill Center",
            "能像 Finder 一样浏览 notebook 对象",
            "能原地编辑真实现有脑图",
            "复习队列和覆盖率是 Card Factory 的必选闭环",
            "外部自动化不能绕过 dry-run、确认、ledger 和回滚",
            "技能包不是自定义 prompt",
            "如果用户的高阶工作仍只能靠输入一句话再点回答下方按钮，就不是终局",
            "跨 notebook 知识层",
            "外部 URL/API 自动化",
        ]:
            self.assertIn(marker, combined)

        for stale in [
            "# Codex Companion Ultimate Design: MN Agent Workbench\n",
            "终极版必须出现的新形态",
            "v2.0 不是“能聊天”就完成",
        ]:
            self.assertNotIn(stale, ultimate)

    def test_ultimate_design_is_not_current_control_inventory(self) -> None:
        ultimate = self.read_doc("docs/ULTIMATE_PLUGIN_DESIGN.md")

        for marker in [
            "终局反证清单",
            "产品断代路线",
            "架构断代",
            "体验断代",
            "数据断代",
            "能力断代",
            "当前预览版 UI 功能验收只证明不退化，不证明 v3 完成",
            "终局验收不按按钮数量算，而按对象覆盖、操作闭环、学习闭环和证据闭环算",
            "如果第一屏仍然需要用户先提问，失败",
            "如果脑图仍然以生成新树为主，失败",
            "如果卡片仍然以回答切块为主，失败",
            "如果拒绝后只能相信日志，失败",
            "如果技能仍然只是 prompt 收藏，失败",
        ]:
            self.assertIn(marker, ultimate)

        for implementation_inventory in [
            "modeSwitchBar",
            "chatModeButton",
            "agentWorkspaceModeButton",
            "modeIntentLine",
            "activeProductMode",
            "lastWorkspacePane",
            "workspaceNavigator",
            "objectBrowserPanel",
            "workflowBuilderBoardPanel",
            "tests/test_knowledge_console.py",
            "tests/test_object_intake.py",
            "tests/test_object_task_composer.py",
            "tests/test_workflow_builder.py",
            "ui_functional_acceptance.py --browser-render --browser-interaction --browser-actions --browser-write-actions",
        ]:
            self.assertNotIn(implementation_inventory, ultimate)

    def test_docs_describe_mindmap_studio_as_operation_workspace(self) -> None:
        combined = "\n".join(
            self.read_doc(name)
            for name in [
                "README.md",
                "README.zh-CN.md",
                "docs/PRODUCT_SPEC.md",
                "docs/USER_MANUAL.md",
                "CHANGELOG.md",
            ]
        )

        for marker in [
            "Mindmap Studio",
            "读取现有脑图",
            "预览 Diff",
            "应用所选",
            "验证事务",
            "回滚事务",
            "不是回答下方按钮的别名",
        ]:
            self.assertIn(marker, combined)


if __name__ == "__main__":
    unittest.main()
